### ISSUE TITLE
Add mod tools to user page

### ISSUE THREAD

**Issue by Tafiti** [LemmyNet/lemmy-ui#111]
If I moderate a community or I am a site admin, the /u/member page should allow for moderation functions like `ban` and `appoint as mod`. Currently the tools are tied to posts or comments a member makes.

This will allow for a better overview of that member profile, like duration on the instance and which other communities or posts the member is making. 

`https://instance.tld/u/member` should have mod tools like `ban` and `appoint as mod`.

**Comment by dessalines** [comment]
I don't know if I like it too much for user pages, because it would require more context about which communities you mod, and a drop down for that, since you aren't in that community. 

I think I'm preferring a community settings page that can do adds and bans from there. Doing mod actions on posts and comments is still easier and better than either of these two.

**Comment by Tafiti** [comment]
From a UI experience, clicking on a /u/member profile felt much intuitive than the three dots. I suppose it is a matter of preference than it is about functionality. Community settings page may resolve this over time. I had not considered that. 

I will close this issue.
