### ISSUE TITLE
Comment Tool Icons Improvement

### ISSUE THREAD

**Issue by Guy-Dudeman** [LemmyNet/lemmy-ui#1121]
Hi there!
I've noticed that on the desktop gui, there is plenty of room to display all the toolbar buttons, but they're hidden behind a "More..." menu:
![image](https://github.com/buresdv/Mlem/assets/136025639/298cbf8d-f04e-40e1-a075-23acd842fd31)
![image](https://github.com/buresdv/Mlem/assets/136025639/08194b1c-c4d8-4c8a-9706-0b5d80cb1f8d)

It seems like an unnecessary click for the desktop user. What's the philosophy behind it? Is it possible to just make all the icons just display instead of hiding half of them?

**Comment by dessalines** [comment]
They could be shown on desktop I suppose.

**Comment by fheft** [comment]
I think hiding icons behind a menu is fair, even if there would be enough space to display them all. 

Reducing 'visual clutter' (too much information and too many buttons) is often a meme when designers overdo it, but it has benefits. Functionality like 'delete comment' or 'view source' are arguably very niche and used seldomly (compared to e.g. up-/downvotes). So _not_ having those icons beneath every comment really helps to emphasize the _relevant_ buttons (voting).

So I think we could discuss which icons belong in the 'relevant most of the time' category, that should be visible all the time. But I personally don't think we should show _all_ icons, just because we have some leftover space.

**Comment by zinklog2** [comment]
Save option should definitely be visible and maybe edit option for your own comments.
