### ISSUE TITLE
Crosspost back links and comment number

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#113]
### Is your proposal related to a problem?

I think the purpose of cross-posting is to reduce duplicates and make people aware of related discussions in other communities, however right now it only shows a single link in the original post.

### Describe the solution you'd like

It would be great if cross-posted topics would also link back to the original topic on the other community, and maybe other communities it was also cross-posted in.

Furthermore a small number behind it showing the number of comments or so would help to see if there is an active discussion about in that community. Maybe cross-post links could also sorted after this comments number so that the most relevant cross-posts are listed first.

**Comment by therealmaxmoon** [comment]
I used Lemmy the first time today and was somehow surprised why the cross-post doesn't work as intended. 

The intuitive way would be, I see an interesting post in group A, which fits perfectly to group B and C. So I create cross-posts. But there is only a link saying where it is from. The comments are separated and it is even possible to make a cross-post chain, which looks even more like chaos, but would at least have a link to all comment sections. A good example is [this post](https://lemmy.ml/post/435153).

The Fediverse was invented to be able to communicate across platforms. But with this, it is even hard to communicate within one platform. 

In my eyes this issue should be reopened and worked on, because it wouldn't only solve the fediverse issue, but would even save resources. Every cross-post needs it's own comment section, instead of linking to the original post and using one thread. 

And comments/discussions wouldn't repeat on every thread, because you can see all comments at once.

**Comment by Nutomic** [comment]
Please dont necrobump old and closed issues. Look for an open issue that describes your problem, or open a new one.

**Comment by therealmaxmoon** [comment]
Ok, instead of necrobumping I will pollute git with the same text as a new issue. :+1:
