### ISSUE TITLE
Back button navigation does not work when create post form fields contain text

### ISSUE THREAD

**Issue by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [LemmyNet/lemmy-ui#1139]
### Issue Summary

When creating a post, using the back button of the browser does not work.

### Steps to Reproduce

1.  Click 'Create a post' and insert some text into the form fields. Alternatively click the crosspost button.
2. Use the browsers back button
3. Observe the url in the navigation bar changing and page content staying the same.
4. Refresh the page with F5. A dialog appears warning you that the form content will be lost.
5. Now the correct page content is shown.

### Technical details
I observed the error on feddit.de using UI: v0.17.3 and BE: 0.17.3.
I am using Firefox 113.0.1
- Any browser console errors?
`Uncaught TypeError: e is not a function
    call https://feddit.de/static/js/client.js:2
    call https://feddit.de/static/js/client.js:2
    i https://feddit.de/static/js/client.js:2
client.js:2:985538
    call https://feddit.de/static/js/client.js:2
    forEach self-hosted:203
    call https://feddit.de/static/js/client.js:2
    i https://feddit.de/static/js/client.js:2
`

**Comment by fheft** [comment]
It seems like the `<Prompt>` component (inferno-router) causes this issue ([post-form.tsx#L195](https://github.com/LemmyNet/lemmy-ui/blob/6227b63ad0ca0382deb2c92a5e8fadccfffb3b92/src/shared/components/post/post-form.tsx#L195)), not sure _why_ exactly though. 

But I think we can just remove it, because its functionality (warning the user about unsaved form input) is already achieved using native browser functionality ([post-form.tsx#L163](https://github.com/LemmyNet/lemmy-ui/blob/6227b63ad0ca0382deb2c92a5e8fadccfffb3b92/src/shared/components/post/post-form.tsx#L163)). 
Even more so, the custom prompt message that `<Prompt>` uses, has no browser support anymore (e.g. removed in [Chrome 51](https://developer.chrome.com/blog/chrome-51-deprecations/)).

If there are no objections I'll make a PR to remove it from all forms.

**Comment by fheft** [comment]
Found out the underlying issue and submitted a fix in the inferno project: https://github.com/infernojs/inferno/pull/1644

**Comment by SleeplessOne1917** [comment]
Should the if statement be checking the when prop instead of the message prop?

**Comment by SleeplessOne1917** [comment]
@e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd I copied the code you used to fix the inferno prompt into a component in lemmy-ui. This should fix the issue. However, I will leave this issue open until the infernojs maintainers merge your fix.

**Comment by trashhalo** [comment]
Related. The nav buttons don't work either. https://github.com/LemmyNet/lemmy-ui/issues/1292#issuecomment-1596279676
