### ISSUE TITLE
[Bug]: Numbered lists don't allow you to select the numbers.

### ISSUE THREAD

**Issue by Kommynct** [LemmyNet/lemmy-ui#1224]
### Summary

Numbered lists can't be copy/pasted on lemmy

### Steps to Reproduce

1. Find a numbered list
2. Select the list
3. Paste elsewhere

You'll find the numbers don't go along with it.

### Version

UI: v0.17.3

**Comment by Nutomic** [comment]
Its the same here on Github. Dont think this can be considered a bug.

**Comment by Kommynct** [comment]
It is more annoying on a public forum, and I don't think it should be that way, regardless, github doing it too I would say is also a bug.

If you do it on word, for example, it does copy the numbers.

**Comment by pproe** [comment]
This is not a bug with Lemmy, nor is it a bug at all. This is the expected functionality for **any website** that uses the `<ol>` html tag.

As a workaround, on Firefox you can highlight the text, _Right Click_ -> "View Selection Source" and copy the underlying html into your new comment/post. AFAIK the only way you can replicate this on chromium/chrome is by viewing the entire page source and finding the list you would like to copy.

**Comment by Kommynct** [comment]
Maybe we should just disable it automatically converting numbered lists? It seems to cause more problems than it solves.

**Comment by pproe** [comment]
Not rendering lists as `<ol>` would greatly reduce accessibility for those using screen-readers, since a vital part of page structure would be out-of-line with web standards. It would also be behaviorally inconsistent with the rest of the internet. 

Your desired functionality can be achieved by using the 'view source' button that is available on a post or comment (see below). This will show the raw markdown, which you can then copy into your own post.

![image](https://github.com/LemmyNet/lemmy-ui/assets/40435390/2d9abbd5-7bbb-4c03-b67a-0744fc799d1e)
