### ISSUE TITLE
Add a way to change default filter on the Communities tab

### ISSUE THREAD

**Issue by urbenlegend** [LemmyNet/lemmy-ui#1244]
### Is your proposal related to a problem?

I usually like to see my subscribed communities first rather than local or all. Every time I click the communities tab, it switches the filter to local.

### Describe the solution you'd like.

I propose that the following additional settings be added:
Default type for Communities: Subscribed, Local, All, Last Selected

This way you can choose the default filter that's shown whenever you click the communities tab. Last Selected essentially saves whatever filter the user was last on and shows it again whenever the communities tab is brought up again.

Similarly, "Last Selected" should be added to "Type" so that we can set the default for posts.

### Describe alternatives you've considered.

I've just manually clicked Subscribed each time I go into communities tab, which gets annoying over time.

**Comment by Rebouz** [comment]
![image](https://github.com/LemmyNet/lemmy-ui/assets/3104276/9d9d5c07-35b2-48ca-827c-b0b3381eeba1)

was this what you meant? Because maybe I'm stupid but if so, sounds like this is already implmented. And I think it works for me. So if it doesn't work for you, it should be labeled as a bug, or otherwise closed.

@urbenlegend

**Comment by alectrocute** [comment]
Related, tracking in: https://github.com/LemmyNet/lemmy-ui/issues/190
