### ISSUE TITLE
[Bug]: Infinite spinner when creating content with image or url

### ISSUE THREAD

**Issue by yaneony** [LemmyNet/lemmy-ui#1289]
### Summary

Followed instructions on how to start with docker. Instance is running well and i can post text without a problem. When i attach image or submit URL no redirect or something happen. Opening second tab to check the posts, after some time new post will appear (10-15 seconds), but the post for will still be there even after 5 minutes. 

### Steps to Reproduce

1. Create new docker instance
2. Start
3. Create new post and attach image

### Technical Details

![2794OY9E](https://github.com/LemmyNet/lemmy-ui/assets/12472001/05ab2ebf-10e6-48f3-9184-60b8f558daa4)

### Version

0.17.4

**Comment by ayan4m1** [comment]
Root cause is likely pictrs not being configured correctly. Check the `pictrs` container logs.

The spinning forever is definitely a UX issue, I tried fixing it locally but the code gets a bit thorny.

Related code is likely https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post/create-post.tsx#L221-L228
