### ISSUE TITLE
[Bug]: Can't logout from voyager.lemmy.ml on Firefox 114.0.1

### ISSUE THREAD

**Issue by beatgammit** [LemmyNet/lemmy-ui#1326]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

I don't know if this is a FE or BE issue, but when I click the logout button on voyager.lemmy.ml, the page simply refreshes. I don't see any failed requests, but I also don't see a specific logout action (the old version seems to request /, but I'm not sure how login/logout is managed).

### Steps to Reproduce

1. login to voyager.lemmy.ml using Firefox
2. logout
3. observe you're still logged in

### Technical Details

I'm using Firefox 114.0.1 on macOS Ventura 13.4.

I see this warning in the console:

> Some cookies are misusing the recommended “SameSite“ attribute.

### Version

0.18.0-rc.1

### Lemmy Instance URL

voyager.lemmy.ml

**Comment by alectrocute** [comment]
That's weird. I'm unable to reproduce, Firefox 114.0.1, 0.18.0-rc.1, macOS 13.4, Apple Silicon. I spent a good few minutes trying to make it happen to no avail. Can you try one more time, now that you've assumably restarted Firefox, etc., and see if the bug is still present? If not, it would be a huge help to close the ticket. Thanks so much!
