### ISSUE TITLE
[Bug] - Having anything else than en-US first in Accepted-Language headers kill the client

### ISSUE THREAD

**Issue by 0xAnansi** [LemmyNet/lemmy-ui#1720]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Seems that the bug returns.

Now, if you setup your browser as accepting, for example, french first so that it sends the header `Accepted-Language: fr-FR,en-US;q=0.7,en;q=0.3`, nothing displays in the UI.

The client does not look for the right path to resolve the reference to the local js file.

```
Uncaught (in promise) Error: Cannot find module './fr-FR'
    a https://jlai.lu/static/9e7fec7/js/client.js:2
    promise callback*a https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    p https://jlai.lu/static/9e7fec7/js/client.js:2
    C https://jlai.lu/static/9e7fec7/js/client.js:2
    w https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    s https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    Ki https://jlai.lu/static/9e7fec7/js/client.js:2
    Zi https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    p https://jlai.lu/static/9e7fec7/js/client.js:2
    C https://jlai.lu/static/9e7fec7/js/client.js:2
    w https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    s https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    Kf https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
```

It should have at least a gracious fallback mechanism since this is not the first time it breaks.

### Steps to Reproduce

1. Open your browser and set its accepted language as French, for example on Firefox:
![image](https://github.com/LemmyNet/lemmy-ui/assets/72401951/45cb1132-7a3d-46c9-9aaf-f78867d64ae8)

Then 

![image](https://github.com/LemmyNet/lemmy-ui/assets/72401951/b70c4d56-ad60-410e-99e3-6bbe051e417b)
2. Load a lemmy instance
3. Look:

![image](https://github.com/LemmyNet/lemmy-ui/assets/72401951/5f2de80d-29bc-4e87-bdbb-9313f3daa527)

4. If you still see content, check in your dev tools that the request is sent with the  header value starting with fr-FR `Accepted-Language: fr-FR,en-US;q=0.7,en;q=0.3`,

### Technical Details

Seems that the client looks for the translation file in the wrong directory again or the file is not named as expected.

```
Uncaught (in promise) Error: Cannot find module './fr-FR'
    a https://jlai.lu/static/9e7fec7/js/client.js:2
    promise callback*a https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    p https://jlai.lu/static/9e7fec7/js/client.js:2
    C https://jlai.lu/static/9e7fec7/js/client.js:2
    w https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    s https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    Ki https://jlai.lu/static/9e7fec7/js/client.js:2
    Zi https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    p https://jlai.lu/static/9e7fec7/js/client.js:2
    C https://jlai.lu/static/9e7fec7/js/client.js:2
    w https://jlai.lu/static/9e7fec7/js/client.js:2
    e https://jlai.lu/static/9e7fec7/js/client.js:2
    s https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    t https://jlai.lu/static/9e7fec7/js/client.js:2
    Kf https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
    <anonymous> https://jlai.lu/static/9e7fec7/js/client.js:2
```

### Lemmy Instance Version

0.18.1-rc5

### Lemmy Instance URL

https://jlai.lu

**Comment by sunaurus** [comment]
Unfortunately there is some different bug at work here, those steps are not reproducing the issue for me:


![image](https://github.com/LemmyNet/lemmy-ui/assets/5356547/4a5f61b0-665d-4ed8-80eb-388fc16d71d0)

Overall the bug seems to only affect a limited amount of users under specific conditions, if anybody can figure out what those conditions are then that would be awesome. I am planning to investigate this further over the weekend.

**Comment by sunaurus** [comment]
Copying a post from a thread on lemm.ee, I have not verified if these steps can reproduce the issue for me or not:

----

I’ve tried to reproduce the steps aswell and it’s kinda tricky because some of the combinations that didn’t work are now just working and I don’t know why.

A way to reproduce it on my end that seems to be pretty reliable so far:

Lemmy language set to browser default and browser set to english, everything works. (I can also set browser default, english, german, doesn’t matter).
Set browser language to german while Lemmy is set to english and restart browser (I’m using chrome btw) Still everything is working.

Now switching back to browser default has it also working as long as I stay on the site. I can refresh the feed by clicking on the lemmy logo, view posts, go back via the lemmy logo etc.
But once I refresh the entire site through chrome, it stops working and I have to change the browser language to english again to set it back up. (It even showed my username at the top right as “Tankon” instead of “Taxxor” for one refresh, the next refresh had the login and sign up buttons, then it was “Taxxor” again on the next^^)

The shorter way would be to have Lemmy set to browser default while having the browser set to english end then switch the browser to german.
But I thought the scenario above where I can still use the site after setting it to browser default as long as I don’t do a full refresh might be of interest to see what the issue might be.

I have this problem on two different systems.

**Comment by RogerSik** [comment]
Same issue here. For me it's working fine on Windows with Edge. But on Android with Edge as browser it's broken like on the first comment described.
