### ISSUE TITLE
View on instance button

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy-ui#1871]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Add a button that will appear on any community page, post, user, etc that is outside the current instance that says "View On Instance". When you click on this button, you will be directed to that page on that instance.

For example, if your on the following URL...

https://lemmy.ml/c/fediverse@lemmy.world

And you click the button, you will be taken to...

https://lemmy.world/c/fediverse

**Comment by SleeplessOne1917** [comment]
This feature already exists. For posts and comments, there are buttons that look like fediverse icons. On communities and user profiles, there is a link on the fully qualified apub name. However, perhaps the UX around these things could be a bit clearer.

**Comment by K4LCIFER** [comment]
UI-wise, the "View On Instance" button's tooltip is not clear at all, as shown in the following picture.

![image](https://github.com/LemmyNet/lemmy-ui/assets/7829231/39b18ec5-89c6-4c43-8c0d-1693d1ba9dd4)

Instead of "Link", the tooltip should say "View On Instance". 

In addition to this, I propose that the "View On Instance" button becomes greyed-out/un-interactable (or, perhaps, simply invisible?), when on the same instance as the post/comment -- it can be confusing to someone that is clicking the button for the first time, out of curiosity, to simply see their page reload, and nothing change.

**Comment by SleeplessOne1917** [comment]
Your suggestions sound like good UX improvements. The "View On Instance" text will require a PR for the translations repo as well.

**Comment by K4LCIFER** [comment]
> Your suggestions sound like good UX improvements. The "View On Instance" text will require a PR for the translations repo as well.

I have created dedicated feature requests for them at #2024 and #2025. As such, this issue can probably be safely closed.
