### ISSUE TITLE
[Feature] Hide "Sign Up" button if signups are disabled for the instance.

### ISSUE THREAD

**Issue by fatflyingpigs** [LemmyNet/lemmy-ui#2078]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

If Registration Mode == Closed Registration, then hide the sign up button. Alternatively, load a variant page that states that signups are closed, possibly with a message from the admins. Message could say something about a temporary close (bot spam, etc.), that the instance is invite only, or another reason.

**Comment by Die4Ever** [comment]
the signup link could also go to https://join-lemmy.org/instances

but I think I like your idea of a custom message better

**Comment by DraconicNEO** [comment]
I don't think it's a great idea to hide the sign up button since it might also confuse users who just can't find it and won't know why, hiding the sign up form and showing a message indicating that Account Creation is disabled as well as a message from the admin optionally explaining why seems like a better solution because it provides an explanation of what's going on to the user.

**Comment by fatflyingpigs** [comment]
Good point - hiding the signup would be very user unfriendly. Since that other issue seems to have a more comprehensive solution, I'll be closing this feature.
