### ISSUE TITLE
lemmy-ui is not sending `local_user_id` in the request to appoint as admin

### ISSUE THREAD

**Issue by NickGeek** [LemmyNet/lemmy-ui#2112]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

lemmy-ui is not sending `local_user_id` in the request to appoint as admin. This will cause a 400 with a deserialisation error from the server due to the missing field.

### Steps to Reproduce

1. Locate a comment or post of a user on your instance
2. Appoint them as admin
3. Witness the 400 error

### Technical Details

Chrome on macOS.

### Lemmy Instance Version

a57658d99c385522328ba8ae5ddaf5d85ffa1475

### Lemmy Instance URL

https://campfyre.nickwebster.dev

**Comment by biosfood** [comment]
Your lemmy server seems to be outdated. In https://github.com/LemmyNet/lemmy/commit/797d26fdf4b9888e61720f72126543df198c1b03, the AddAdmin function was changed back to accept a  PersonId, because a local_user_id typically is not available from the clients (it's not provided in the getPost query).

Updating the server should fix this problem. Just make sure your lemmy-ui is at or newer than 8e2609a96d7d939f6f55ccb794513e10252fabb7

**Comment by NickGeek** [comment]
Ah thanks, I'll update.
