### ISSUE TITLE
You appear to be able to post on a PeerTube channel's page

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2161]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

It seems that PeerTube channels are federated as communities to Lemmy. These communities are open to anybody so it appears that you can post to them. I'm not sure what effect this has, but it certainly does not seem to be intended behaviour. [This channel](https://lemm.ee/c/thelinuxexperiment_channel@tilvids.com)'s page on Lemmy is an example of this.

### Steps to Reproduce

1. Find a PeerTube channel on Lemmy
2. Go to that channel's "Community"
3. Observe that you can make a post

### Technical Details

- OS: Arch Linux
- Browser: Firefox 118

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

lemm.ee

**Comment by JessFairbairn** [comment]
Has anyone tried what this actually does?

I suppose this means Peertube is listing their channels as Groups rather than Users according to the activitypub standard, which is a bit of a surprise to me. (For example, [this is how Lemmy flags up that something is a community rather than a user](https://github.com/mastodon/mastodon/issues/17008#issuecomment-1445002386))

I'm new to activitypub so take this all with a pinch of salt

**Comment by SleeplessOne1917** [comment]
This seems more like a backend issue than a frontend issue.
