### ISSUE TITLE
Community mod ban list

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#2328]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I've gotten complaints from community moderators that moderation their communities is made more difficult from the UI. One of the changes that should really help is allowing community mods to review lists of who is banned.

**Comment by Asudox** [comment]
You can sort by action in the modlog. So you can just sort by the ban action and you get all the bans.

**Comment by Gobtous** [comment]
I might be off topuc, sorry. Why not putting modlog alongside moderator view ? Or the shield ? This button would only appear if you are a moderator of this community ? 

Or merge them in moderator's view and add some filters buttons below the moderation timeline  : 
* ban/delete/pin/featured/new comment/new post 
* this community/this instance/lemmyverse
* last read/recent

**Comment by Iceblade02** [comment]
Ideally it should also be possible to do enact moderation actions on banned users via this menu. I'm aware of cases where users have been wrongfully "purge banned" (a ban that removes all posts & comments of a user in a community), and it is impossible to lift such a ban since the user no longer has any posts/comments in the relevant community.

**Comment by dessalines** [comment]
> You can sort by action in the modlog. So you can just sort by the ban action and you get all the bans in a community.

Yep I think that already accomplishes this. Filter by community and ban action.

**Comment by DraconicNEO** [comment]
I know this is old but I do think it would be important to have a list of who's banned in the settings with options to unban them there. Bans can get lost in the modlog, and sometimes fail to appear in the modlog for one reason or another. Having a dedicated page in the new community settings to see the bans and possibly remove them would be a good thing to have, especially to make it easier to unban users since currently you can only do so from the comments they make which is extremely clunky.

**Comment by Nutomic** [comment]
We have a user list for admins now, and also a settings page for users. So it shouldnt be too hard to add a similar user list for community mods too, probably sometime after 1.0 is released.
