### ISSUE TITLE
[Bug]: Delete Account should delete uploaded media (pictures) too

### ISSUE THREAD

**Issue by maltfield** [LemmyNet/lemmy-ui#2384]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Bug: When a user deletes their account in Lemmy, they're told that it will "permanently delete all of your data from this instance" but, in fact, it doesn't delete all of their data. For example, the photos that they uploaded will not be deleted.

When a user deletes their account in Lemmy, they're presented with the following message

```
Warning: this will permanently delete all of your data from this instance
```

Users should expect then, that all of their data was deleted. But this is not the case for photos.

This means that all instance admins are violating the laws of GDPR for any users that live in the European Union.

### Steps to Reproduce

1. Create a new account on lemmy
2. Upload a picture to the instance (eg by creating a post and entering an image to upload)
3. Save the URL of the uploaded image
4. Delete the lemmy account
5. Confirm that the user no longer exists (eg visiting their old profile page should return a 500 error)
6. Confirm the uploaded image is not deleted (eg in a cache-cleared web browser, visit the URL of the uploaded image)

### Technical Details

Linux, Firefox

### Version

BE 0.19.3

**Comment by Nutomic** [comment]
Unfortunately there was some miscommunication in this issue and we failed to get to the root cause. In fact the Lemmy backend has an option to delete all content when an account is deleted. This used to be the default behaviour but [was changed](https://github.com/LemmyNet/lemmy/pull/3817) in 0.19 so you need to set a parameter `delete_content`. We failed to add a checkbox for this parameter to lemmy-ui.

However the checkbox is added now in https://github.com/LemmyNet/lemmy-ui/pull/2385 and will be included in the next Lemmy release. Other frontends and clients may also need to adjust the delete_account api call.

**Comment by Zamirk** [comment]
_Popcorn, popcorn, get your popcorn! Freshly popped with golden butter and just a pinch of salt_ 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿 🍿

**Comment by Security-Chief-Odo** [comment]
> learn Rust

Yep, that's a pre-requsite to contributing to Lemmy codebase.  But you misunderstand how accessible that is versus someone or a team working on their own, less obscure language alternative. If it comes down to _just learn Rust only for the opinionated devs to say @#$#$ off_ or _help contribute to a project with a well established language and _receptive) developers... well then... I know where my energy is better spent. 

Good luck Lemmy; you'll need it.
