### ISSUE TITLE
When delete button is in dropdown menu, the menu disappears before completion

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#2406]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Selecting "delete" here causes the menu (which includes the loading indicator then the "undelete" button) to disappear.

![IMG_1625](https://github.com/LemmyNet/lemmy-ui/assets/47706471/5de7aaa0-e57f-42b8-a5ee-98b9012eda0c)

### Steps to Reproduce

1. Press 3 dots
2. Press delete
3. Menu disappears and UI gives no feedback about deletion
4. Press 3 dots
5. See loading indicator and/or "undelete", which should have been seen earlier

### Technical Details

iPhone, iOS 17.3.1

Safari with desktop mode

(i don't endorse this environment)

### Lemmy Instance Version

0.19.3

### Lemmy Instance URL

https://lemmy.ca

**Comment by SleeplessOne1917** [comment]
This happens for all of the options in that dropdown, not just delete. I'm not even sure if we should consider this a bug, since it's not often a user will want to use more than one action at a time. It's arguably better than leaving the dropdown open since it saves the user the need to perform an extra click to dismiss it.

Also, this behavior is how bootstrap handles things. Implementing this will require fighting against the framework for little to no benefit.

**Comment by dullbananas** [comment]
The loading indicator could be moved out of the dropdown menu.

**Comment by SleeplessOne1917** [comment]
@dessalines @MV-GH thoughts on this? There is already a toast for when a delete is successful. I'm not convinced a spinner outside the dropdown is a better experience, but I could use the input of people who've worked on UIs to help make a decision.

**Comment by dessalines** [comment]
Ya I agree, as long as there's a toast, this is a non-issue.
