### ISSUE TITLE
Inbox doesn't work if it's the first page to be viewed

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#2601]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you start at the homepage then use the inbox button, then it works.

If you start with the inbox URL (e.g. when clicking the "inbox" link in an email), then it asks you to log in.

### Steps to Reproduce

1. Go to a new browser tab that doesn't already have Lemmy open
2. Go directly to the /inbox URL

### Technical Details

Safari from iOS 17.5.1

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

https://lemmy.ca

**Comment by SleeplessOne1917** [comment]
This doesn't sound like a bug. How could a non-logged in user see an inbox when inboxes are associated with accounts?

**Comment by dullbananas** [comment]
This happens when I'm logged in

**Comment by SleeplessOne1917** [comment]
I'm unable to reproduce this issue both locally and in production testing with firefox. Do you run into this issue with other browsers, or only Safari?

**Comment by dullbananas** [comment]
It randomly started working correctly a minute ago

**Comment by dullbananas** [comment]
I just got an email notification and I had this problem again with the inbox link

**Comment by SleeplessOne1917** [comment]
When it happened last time, was that also from following an email link?

**Comment by dullbananas** [comment]
Yes

**Comment by SleeplessOne1917** [comment]
I've finally gotten around to trying to fix this and am running into a lot of trouble trying to test this locally. I am unable to set an email for a user when testing this locally. I tried adding the email config from `./config/defaults.hjson` to `./docker/lemmy.hjson` and even then I'm unable to set it. @dullbananas  Does this happen any time when following a link that isn't sent via email? Otherwise, I'm not sure how to go about reproducing the issue, and I don't think this should hold up the 0.19.6 release if that's the case.

**Comment by dullbananas** [comment]
Based on the "steps to reproduce" list, it seems like I was able to replicate it without email a while ago, but I haven't been able to do that recently.

I don't remember ever seeing the unexpected log in screen load instantly, and last time I manually opened the inbox URL it did load instantly, so I suspect that it could be reproduced by opening that URL after not opening Lemmy for a while if a cache normally prevents the bug.

**Comment by dullbananas** [comment]
I can replicate it by sending myself an email with the link, opening in in the gmail app, then selecting "default browser" in the "open with" menu

**Comment by SleeplessOne1917** [comment]
Are you replicating this in production or locally? I've had trouble setting up the config to send emails when I'm running the app locally.

**Comment by dullbananas** [comment]
I'm using lemmy.ca and the email doesn't need to be from a real notification, it can be an email sent from yourself that just contains the /inbox url

**Comment by dessalines** [comment]
You'd need to test this against one of the test servers running the beta like voyager.lemmy.ml . Lets just push this one back to `0.20.0` milestone.

**Comment by SleeplessOne1917** [comment]
I finally figured out the cause of this issue. It turns out this is a consequence of setting `SameSite` to strict for the session cookie. This can be fixed by using lax instead. I'm not sure if this will warrant some extra CSRF protection or not.

**Comment by dessalines** [comment]
> It randomly started working correctly a minute ago

We're getting this on newer versions of firefox intermittently also: #2666

I don't understand why `sameSite: Strict` is causing either of these tho. You're navigating to a site that should already have your cookie stored locally, no cookie needs to be sent from one site to another.

**Comment by SleeplessOne1917** [comment]
> I don't understand why sameSite: Strict is causing either of these tho. You're navigating to a site that should already have your cookie stored locally, no cookie needs to be sent from one site to another.

The link you posted actually explains why that is the case:
> Let's say a user is on site-a.com and clicks on a link to go to site-b.com. **This is a cross-site request**. This is a top-level navigation and is a GET request, so **Lax cookies are sent to site-b.com. However, Strict cookies are not sent because it is, after all, a cross-site request.**

Emphasis mine.

Clicking a link to a site from an email is considered a cross site request. Since the session cookie's `SameSite` attribute is set to strict, it will not be sent for this request. The same thing happens if you click a fedilink on one instance that leads to another instance where you are already logged in. When you get to the other instance, you will not be logged in, but if you refresh the page (at least in browsers where the issue you linked isn't present), you will be shown as logged in since it is a same site request.

**Comment by dessalines** [comment]
Still doesn't make too much sense to me (no cookies need to be sent anywhere), but to me this means that `SameSite: strict` is essentially useless because it means no one can navigate to your site from anywhere, and appear logged in. 

We've been using sameSite:strict for a long time now and I've never seen this issue.

**Comment by dessalines** [comment]
https://web.dev/articles/samesite-cookies-explained

This link uses the *send* verb to mean sent from the browser to your site, not sending between different sites, so I think we should be okay with sameSite: Lax.
