### ISSUE TITLE
Add option to open links in a new tab

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy-ui#282]
I’ve noticed, that links are always being opened in the same tab and after reading you should all the time return to the lemmy page back, which is annoying.

Here is discussion regarding this issue on lemmy: https://lemmy.ml/post/62429

It would be great either to open post's link in a new tab by default or at least have such option in settings.

**Comment by dessalines** [comment]
I used to have it that way by default, but it turns out that's a violation of accessibility. I just use middle mouse click now. If anyone wants to add a setting for this tho, go right ahead.

**Comment by LongJohn-Silver** [comment]
> I used to have it that way by default, but it turns out that's a violation of accessibility. I just use middle mouse click now. If anyone wants to add a setting for this tho, go right ahead.

Me too, but I notice the place where you are supposed to click is a bit finicky, I think it only works when you click on the symbol, not the whole square, do you think that could be changed at least?

**Comment by loid345** [comment]
> I used to have it that way by default, but it turns out that's a violation of accessibility. I just use middle mouse click now. If anyone wants to add a setting for this tho, go right ahead.

violation of accessibility... Is there a way around this? It is impossible to use the platform if the platform is a link aggregator. We constantly have to go back. Reddit doesn't have this behavior when clicking on links
for example https://www.reddit.com/r/leagueoflegends/comments/p9jvfc/spoiler_adam_explains_how_scrims_went_against/

**Comment by LongJohn-Silver** [comment]
I think my previous comment wasn't that concise, so I think except for images, it works great, but when there's a picture and I want to open it in a new tab to download it or whatever, I need to click on this part of the image:

![Screenshot from 2021-08-27 21-34-11](https://user-images.githubusercontent.com/63723030/131200533-a63995dc-1d9d-4484-bd35-fedaf75fbcf7.png)
![Screenshot from 2021-08-27 21-34-18](https://user-images.githubusercontent.com/63723030/131200537-12cbe7ca-45fb-4cb5-ab4b-4d602787bbfd.png)

Which is all fine and good, but in order to so I have to click exactly in the image icon within the grey box, which is pretty hard, so ideally the whole gray box should be clickable, not only the icon within it.

**Comment by dessalines** [comment]
> violation of accessibility... Is there a way around this? It is impossible to use the platform if the platform is a link aggregator. We constantly have to go back. Reddit doesn't have this behavior when clicking on links
for example https://www.reddit.com/r/leagueoflegends/comments/p9jvfc/spoiler_adam_explains_how_scrims_went_against/

I just tested this out on old reddit, and it does appear to work in the accessible way. New reddit removed the accessibility requirement there. Also, its not difficult to right click -> open in new tab, or middle mouse click.

> Which is all fine and good, but in order to so I have to click exactly in the image icon within the grey box, which is pretty hard, so ideally the whole gray box should be clickable, not only the icon within it


@LongJohn-Silver Yes you're correct, looks like something is broken there with image posts. I do hijack that clicking to expand within the page itself, so that's probably why, but there's probably a way to fix it. If you could paste your comment into a new issue that'd be helpful.

**Comment by loid345** [comment]
> I just tested this out on old reddit, and it does appear to work in the accessible way. New reddit removed the accessibility requirement there. Also, its not difficult to right click -> open in new tab, or middle mouse click.
> 
On a desktop computer, I agree, but more than 80 % of the traffic comes from a mobile phone. There is no mouse there

**Comment by fvbommel** [comment]
> I just tested this out on old reddit, and it does appear to work in the accessible way.

On old Reddit it appears to be a setting: preferences => clicking options => open links in a new window.

**Comment by Denaton** [comment]
Best practice is to never redirect the user away from the site.

**Comment by k5jat** [comment]
> Best practice is to never redirect the user away from the site.

This has been my philosophy since they added the tag to do it. It used to open a new window, until we got tabs. I love that we can open a new site in a tab, and ww can just click back on my site's tab to continue their experience like they never left. It makes things a bit more simple.

**Comment by krestenlaust** [comment]
I can't take it anymore. This is so annoying. I might try to make a PR for this. The claims of this being an accessibility feature are unfounded, it goes against the very laws of the internet.

**Comment by CraigHB** [comment]
Would like to add that I'd really like an option for "open links in new tab".  It's top of the wishlist for me.

**Comment by Dogeek** [comment]
I'm actually working on it as we speak @krestenlaust

**Comment by d42ohpaz** [comment]
@Dogeek any status update on your progress?

**Comment by Dogeek** [comment]
https://github.com/LemmyNet/lemmy-ui/pull/1546

**Comment by SineSwiper** [comment]
Aaaand it's closed without merge. So disappointing.

The workflow of trying to read comments without new tabs is broken:

1. Go on front page.
2. Go to Page 2.
3. Click on comments for a post.
4. Read comments.
5. Click Back button.
6. Get dumped back to **Page 1** on the front page.

This is especially annoying when you're a few pages deep and are trying to figure out how to get back there. Automatically opening new comments in tabs would side step this problem.

**Comment by Dogeek** [comment]
I closed it cause I have no interest in having to battle dessalines on minor nitpicks. Feel free to take the branch and reopen the pull request.

My thought process was that since lemmy is open source, we should be free to add new features without having to battle over philosophies, which was made apparent to me with his reviews and very strong opinions over which features to greenlight and which features to debate at length over (see infinite scrolling, and this very issue which was only approved on the condition we make it a setting that is off by default). I just don't have the energy to contribute and be challenged on every little thing, I'll just remain a plain user of the platform and not bother contributing to the project anymore.

**Comment by Security-Chief-Odo** [comment]
> Best practice is to never redirect the user away from the site.

Then what's the point of being a _LINK_ aggregator?

**Comment by dessalines** [comment]
Fixed by #2032
