### ISSUE TITLE
Collapse comments button is not intuitive

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#318]
Turns out its the dash next to the username. I didnt even know thats a button.

**Comment by dessalines** [comment]
I spose the minus-square might be more obvious. https://feathericons.com/?query=minus

**Comment by Nutomic** [comment]
I think the minus-square in that link is better, with the border it looks more obviously like a button. Also someone mentioned that there is currently no hover text.

**Comment by JediMaster25** [comment]
I still found the collapse button isn't intuitive. The one in libreddit seems more intuitive. It changes from a down arrow when it shows the comment to a right arrow when it's collapsed. I think showing the total votes on the left instead of the avatar is also better but that's just personal preference.

![Screenshot from 2023-01-21 00-44-17](https://user-images.githubusercontent.com/105824751/213825074-2379d2a2-8dd4-4171-acd4-830cb4c2e793.png)
![Screenshot from 2023-01-21 00-44-34](https://user-images.githubusercontent.com/105824751/213825063-f4e0038f-4662-4d84-bfe2-6ad99d32140f.png)

**Comment by dustojnikhummer** [comment]
Lemmy really needs it's own RSS. Text labels are better than icons
