### ISSUE TITLE
Prevent reloading when going "back" from a post (cache)

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy-ui#338]
### The problem

Clicking "back" from a post, has to reload the previous page's index call

### The solution I'd like

Cache the previous page's index call so navigating back from a post is instant

### Alternatives I've considered

Making "post pages" modal like on the newly redesigned reddit ui

### Additional context

you guys rock <3

**Comment by dessalines** [comment]
I've avoided front page caches, not only because they don't make much sense for a live-updating application, but also because they're more difficult to implement in an SPA, where we can't take advantage of the back button using the old stored page.

In chat apps they make more sense because data is shown in a linear way: but in lemmy we have to resort the front page for new content anyway.
