### ISSUE TITLE
Page reload flashes default theme

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#45]
This can be very noticable when a theme different from the default `lightly` is configured. Usually the page reload is almost instant, but sometimes it takes a second or more for the correct theme to be applied, so that buttons flash up in green. Sometimes even the background stays white for a noticable time before darkly is applied.

This problem only started to happen after the isomorphic ui rewrite, not before.

Happens with Firefox and Firefox Android.

**Comment by dessalines** [comment]
I might not be able to do anything about this one. You only didn't notice it before this isomorphic UI because darkly was the default theme, and it didn't load anything if that was your chosen theme. But now the default theme is `browser default` in that dropdown, IE either darkly or litely depending on your browser. If you have anything else set, it has to unload those ones and load your custom theme on-demand after the page is loaded (There's no way around this unless I added every theme to the index.html and thus greatly increase the page size).
