### ISSUE TITLE
Theme and other settings for logged out users

### ISSUE THREAD

**Issue by leslieriver** [LemmyNet/lemmy-ui#512]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

logged out users can't change theme or make use of other useful settings.

### Describe the solution you'd like

looks like all settings are handled by the api. make use of local storage instead

**Comment by dessalines** [comment]
> logged out users can't change theme or make use of other useful settings.

This isn't anything I want to support. User settings require a user, and it takes less than a minute to create one and have settings.

> looks like all settings are handled by the api. make use of local storage instead

Hard no on this, I intentionally made settings portable, so that they can follow you to whatever device you log in from. I can't stand the localstorage model of having to change your settings for every new browser and device you use.

**Comment by leslieriver** [comment]
> This isn't anything I want to support. User settings require a user, and it takes less than a minute to create one and have settings.

k. agree for all other settings except theming, there is no reason to force a login to use a preferred theme, it's lemmy-ui specific too so it doesn't really make sense to have it in  the api anyway. 

 > Hard no on this, I intentionally made settings portable, so that they can follow you to whatever device you log in from. I can't stand the localstorage model of having to change your settings for every new browser and device you use.

fine, you can add  a 'BrowserSettings' alongside it though, there are other settings that make sense to be browser specific like #282
