### ISSUE TITLE
Add config option to change default theme

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#559]
So that instance admins can choose which theme users get by default, instead of litely. This would allow for some easy costumization, cause its really boring if all instances look identical.

**Comment by dessalines** [comment]
This would be a back-end setting, and a column on the site table.

**Comment by Nutomic** [comment]
The backend only stores the theme in user settings if a user manually selected a different one. But in case there is none selected, or a user is not logged in, the frontend can decide on its own which theme to use. Setting the default in the backend seems unnecessarily complicated, and doesnt really give any benefit. Plus i would prefer not to couple lemmy too tightly with lemmy-ui, as it should be possible to write alternative frontends.

**Comment by dessalines** [comment]
There is already a theme column in the `local_user` table, default `browser`, so this would be easy enough to add to the site table. 

The reason I don't like putting business logic on the front end, is it means you lose portability. So all reddit clients for example, because reddit refuses to add UI / themes / other preferences like default sorts to the back end, means each reddit app or client now needs its own database, settings, etc for your user, that are lost with each login and new app. This is even relevant for android or iOS clients, because without back-end settings, every single log-in means you have to update your user preferences again, because the back-end didn't store them. Its def annoying to have to do this with reddit clients.

Having a front end config would also mean yet another config location to our already 3 existing: docker, lemmy.hjson, and the site edit.

I'd rather app devs request local user settings, or site settings, and us be flexible with adding them to the API, and not have them be front end configs.

Also with this specifically, having it be a front end config, means we lose the ability for an admin to change it through the UI.
