### ISSUE TITLE
Have the subscript and superscript not be limited to words

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy-ui#561]
Sometimes when writing, we usually tend to find ways of organizing and presenting our ideas when communicating to others. The use of subscript and superscript are very useful when structuring footnotes in comments, if necessary or relevant. A footnote is sometimes necessary when talking about complex subjects (and makes reading much easier than with a three line parenthesis).

Also a related request is to have the options for "big" and "small" in text to give poster options to enhance their posts with effects and further expression

**Comment by quazar-omega** [comment]
The issue was raised on the superscript repo https://github.com/markdown-it/markdown-it-sup/issues/3, but it was closed as won't fix, while the reason makes sense, I'd say the spec itself is bad, because you'd have to type a lot of extra characters just to write a superscript sentence. I find this behavior counterintuitive since other markers span the whole space-separated sentence, then it gets extremely annoying the more text one has to write.  
Is there any chance that this could be checked out again? Maybe using the `<sup>` (and `sub`) [HTML tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup), I don't know if that's a better way to handle it
