### ISSUE TITLE
Document env vars

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#661]
The env vars lemmy-ui uses should be documented in the README, and also prefixed uniformly by `LEMMY_UI` .

**Comment by Nutomic** [comment]
Actually, i think it would be much clearer to use another config file for lemmy-ui, instead of countless env vars. That would also allow for documentation right next to it, and generally make management easier. For example, you cant easily edit docker-compose.yml to add an env var if its deployed via ansible
