### ISSUE TITLE
Make lemmy-ui work when deployed to subfolder

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#727]
For the initial, selfhosted deployment of [LemmyBB](https://github.com/LemmyNet/lemmyBB), I plan to ship it with lemmy-ui hosted in a subfolder, to provide access to moderation tools, and other features which are not yet implemented in LemmyBB. 

Unfortunately lemmy-ui is currently not working in this setup, as you can observe under [lemmybb.lemmy.ml/lemmy-ui](https://lemmybb.lemmy.ml/lemmy-ui). The problem is that absolute paths are used for everything, when relative paths would be necessary. In particular, I noticed the following problems:
- assets are loaded from `/static` and `/css`
- links point to `/login`, `/register` etc
- directly accessing a path like `/lemmy-ui/login` gives error 404

Code is [here](https://github.com/LemmyNet/lemmyBB/pull/7), and its currently installed on our test server in `/lemmy/lemmyBB`.

In my opinion, this is the only thing blocking lemmy-ui from being released for selfhosting.

**Comment by dessalines** [comment]
I'm realizing now there'd have to be a lot of code changes, since there's a ton of navigation that also relies on top level routes, in addition to webpack changes and a whole lot more. I think its best to just say lemmy-ui can't be hosted in a subfolder, and needs its own domain, most self-hosted services are like that anyway.
