### ISSUE TITLE
Language setting hiding most posts

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#917]
After choosing english as the default language in the settings I stopped seeing all previous posts that weren't tagged with a language. At least I think it is because of that.

I chose the setting so that I didn't have to choose a language every time I created a new post but I didn't want to stop seeing the rest of the posts.

I would like to choose independently the default language for new posts and the list of languages I want to see in the feed.

**Comment by ashemsay** [comment]
I second this, I though for a moment I had an issue with my federation but eventually remembered I had changed this setting.
This is very disturbing.
At the very least some warning that messages have been hidden due to this setting could be nice.
Also the label could be clearer, "Visible languages" instead of just "Languages" for example.

**Comment by dessalines** [comment]
> At the very least some warning that messages have been hidden due to this setting could be nice.
Also the label could be clearer, "Visible languages" instead of just "Languages" for example.

@ashemsay could you open this up as a separate issue, if one doesn't already exist. A warning icon with a popup would probably be the best way to handle this.
